### ISSUE TITLE
Atmospheric chlorine

### ISSUE THREAD

**Issue by dan-visioni** [krpetlock/SAI-Ozone-depletion-KP#4]
Updating chlorine values based on NOAA database
https://gml.noaa.gov/hats/odgi.html

The code now reads the xls file and uses values for last available year (here, 2021)

We can now add different projections for the future.

**Comment by krpetlock** [comment]
I see the approximate yearly rate of decline plotted in fig 2.  I thought I saw more interannual variability in Cl (up and down) projected somewhere, but maybe I'm confusing it with another parameter.  In fig 2 it looks like the rate of decrease in Cl concentration is around 30-40 PPT, which is significantly more than what I had in the code (8.2) from another source.  Looks like this NOAA data is more up to date(?).
