### ISSUE TITLE
CESM ClOx driven loss

### ISSUE THREAD

**Issue by dan-visioni** [krpetlock/SAI-Ozone-depletion-KP#6]
I added some new code to analyze ClOx-driven O3 loss in CESM from our simulations described in https://www.pnas.org/doi/10.1073/pnas.2202230119

(I couldn't add the NetCDF file because it was giving me problem. I'll email)

You can check the figures however: 
values are various oom higher than what calculated by your code.
Now we need to figure out if we're comparing like with like, and how to reconcile/

**Comment by krpetlock** [comment]
Okay
